# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI/CD with Gradle and Deploy to Heroku

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        working-directory: ./homeworks/hw6
        run: chmod +x gradlew
      - name: Grant database permissions
        working-directory: ./homeworks/hw6
        run: chmod 777 MyBooksApp.db
      - name: Build with Gradle
        working-directory: ./homeworks/hw6
        run: ./gradlew build jar
      - name: Commit to the repo
        uses: EndBug/add-and-commit@v4.4.0
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hidden-shore-35596" #Provide your unique app name here
          heroku_email: "chenyu.heidi.z@gmail.com" #Provide your Heroku email address here
